version: '3.9'

services:
  #node application
  api:
    container_name: api-node
    build: ./docker-script/api/
    ports:
      - 3000:3000
  #load balancer
  nginx:
    container_name: proxy_lb
    build: ./docker-script/nginx/
    depends_on:
      - api
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443